module.exports = {
  content: [
    "html/Acceuil.html",
    "html/avis.html",
    "html/cafard.html",
    "html/cave-local.html",
    "html/deces.html",
    "html/depigeonnage.html",
    "html/destruction.html",
    "html/dératisation.html",
    "html/fouine.html",
    "html/fourmis.html",
    "html/frelon.html",
    "html/gale.html",
    "html/galerie.html",
    "html/puce.html",
    "html/punaise.html",
    "politiques/condition.html",
    "politiques/cookie.html",
    "politiques/mention.html",
    "politiques/politique-de-conf.html",
    "politiques/qui-sommes-nous.html",
    "politiques/securite.html",
    "contact/contact.html",
    "contact/contact25.html",
    "contact/contact70.html",
    "contact/contact90.html",
  ],
  css: [
    "css/anim-galerie.css",
    "css/avis.css",
    "css/politique.css",
    "css/produit.css",
    "css/style-acceuil.css",
    "css/style-contact.css",
  ],
  keyframes: true,
  output: "dist/css",
  rejected: true,
  variables: true,
};
