module.exports = {
  content: [
    "htmlAcceuil.html",
    "htmlavis.html",
    "htmlcafard.html",
    "htmlcave-local.html",
    "htmldeces.html",
    "htmldepigeonnage.html",
    "htmldestruction.html",
    "htmldératisation.html",
    "html\fouine.html",
    "html\fourmis.html",
    "html\frelon.html",
    "htmlgale.html",
    "htmlgalerie.html",
    "htmlpuce.html",
    "htmlpunaise.html",
    "politiquescondition.html",
    "politiquescookie.html",
    "politiquesmention.html",
    "politiquespolitique-de-conf.html",
    "politiquesqui-sommes-nous.html",
    "politiquessecurite.html",
    "contactcontact.html",
    "contactcontact25.html",
    "contactcontact70.html",
    "contactcontact90.html",
  ],
  css: [
    "cssanim-galerie.css",
    "cssavis.css",
    "csspolitique.css",
    "cssproduit.css",
    "cssstyle-acceuil.css",
    "cssstyle-contact.css",
  ],
  Keyframes: true,
  output: "purgecss.config.js",
  rejected: true,
  variables: true,
};
